version: '3'
services:
  flask:
    build: ./flask
    ports:
      - 5000:5000
    depends_on:
      # 先に db コンテナを立ち上げる
      - psql
  psql:
    # localhost と接続するわけではないので expose を使う
    build: ./postgres
    expose:
      - "5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    volumes:
      - ./postgres/initdb:/docker-entrypoint-initdb.d
      - database:/var/lib/postgresql/data
volumes:
  database:
    driver: local